### ISSUE TITLE
Does this work?

### ISSUE THREAD

**Issue by pavanagrawal123** [WesJones127/rh-dash#2]
Hi! 
Is there a Readme for this project?

What functionality does it have?
Do you have any instructions for getting it installed?

Project looks super awesome!

Thanks!

**Comment by WesJones127** [comment]
Hi, this is a side project that I recently started working on.  It's not in a usable state yet.  

I don't have immediate plans to add trading functionality to this system.  The goal right now is just to be able to see your current investments and watchlists on the browser instead of having to use the phone app.
